# -*- coding: UTF-8 -*-

field_names_main = {"標題": "title", "摘要": "notes"}
field_names_extras_free = {"起始時間": "start_time", "結束時間": "end_time",
        "識別碼": "identifier", "主題關鍵字 1": "theme_keyword_1",
        "主題關鍵字 2": "theme_keyword_2", "主題關鍵字 3": "theme_keyword_3",
        "主題關鍵字 4": "theme_keyword_4", "主題關鍵字 5": "theme_keyword_5", "作者": "author_name",
        "作者的電子郵件": "author_mail", "作者聯絡電話": "author_phone", "維護者": "maintainer_name",
        "維護者的電子郵件": "maintainer_mail", "維護者聯絡電話": "maintainer_phone",
        "空間範圍.X.min": "x_min", "空間範圍.X.max": "x_max", "空間範圍.Y.min": "y_min",
        "空間範圍.Y.max": "y_max", "空間範圍": "spatial", "參考來源": "ref",
        "ISBN-13": "book_isbn", "ISSN": "book_issn", "期刊": "book_journal",
        "卷期": "book_volume", "論文集名稱": "book_proceeding", "出版地": "book_location",
        "出版社": "book_publisher", "出版年": "book_year", "書目查詢": "book_query",
        "原文網址": "book_url", "研究區的聚落名": "book_area_village",
        "研究區的宗教": "book_area_religion", "研究區的家族": "book_area_family",
        "研究區的埤圳": "book_area_reservoir", "研究區的特殊產業": "book_area_industry",
        "備註 (文獻書籍)": "book_notes", "掃描原件來源": "scan_source",
        "掃描原件尺寸": "scan_size", "掃描解析度": "scan_res", "座標參考系統": "crs",
        "空間解析度": "spatial_res", "比例尺": "scale", "資料處理歷程": "preprocessing"}
field_license_id = {"id": "license_id", "授權類型未指定": "notspecified",
        "開放資料共用公共領域貢獻和授權條款 (PDDL)": "odc-pddl",
        "開放資料共用開放資料庫條款 (ODbL)": "odc-odbl", "Open Data Commons Attribution License": "odc-by",
        "公眾領域貢獻宣告 (CC0)": "cc-zero", "創用 CC 姓名標示 (CC-BY)": "cc-by",
        "創用 CC 姓名標示-相同方式分享 (CC-BY-SA)": "cc-by-sa", "GNU 自由文件授權條款(GFDL)": "gfdl",
        "其他(開放)": "other-open", "其他(開放)": "other-pd", "其他(姓名標示)": "other-at",
        "UK Open Government Licence (OGL)": "uk-ogl", "創用 CC 非商業性": "cc-nc", "其他 (非商業性)": "other-nc",
        "其他 (非開放)": "other-closed"}
options_hist_material = {"清代方志": "book_from_local_chronicles_in_qing_dynasty",
        "日治出版品與官方資料": "book_from_japan_officials",
        "戰後官方資料與鄉鎮志": "book_from_officials_in_postwar_period",
        "碑文": "book_from_inscriptions", "報紙": "book_from_newspapers",
        "地圖": "book_from_maps",
        "台灣總督府檔案": "book_from_taiwanese_governor_office_files",
        "荷治時期檔案": "book_from_dutch_formosa",
        "地方田野收集文獻": "book_from_field_researches"}
groups = {"生物生態類": "biota", "土地邊界類": "boundaries",
        "氣候氣象類": "climatology-meteorology-atmosphere",
        "環境活動類": "environment", "經濟活動類": "economy",
        "高程資訊類": "elevation", "健康衛生類": "health",
        "地球科學相關類": "geoscientific-information",
        "農業相關類": "farming", "水文資訊類": "inland-waters",
        "軍事情報類": "intelligence-military",
        "地表覆蓋資訊類": "imagery-base-maps-earth-cover",
        "土地使用與規劃類": "planning-cadastre",
        "海洋資訊類": "oceans", "位置資訊類": "location",
        "交通資訊類": "transportation", "人工設施類": "structure",
        "社會文化類": "society", "公共設施類": "utilities-communication"}
